services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile.local
    pull_policy: never
    ports:
      - 3000:3000
      - 51212:51212
    volumes:
      - ./server:/app
    networks:
      - localstack_network
    depends_on:
      - localstack
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
      - '127.0.0.1:443:443' # LocalStack HTTPS Gateway
    environment:
      # Activate LocalStack for AWS: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localstack_network
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=blogging-app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - localstack_network
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - database
    ports:
      - 8080:8080
volumes:
  postgres_data:
networks:
  localstack_network: